PygmentsUseClasses = false
PygmentsStyle = "colorful"
baseurl = "https://tiernano.github.io"
enableRobotsTXT = true
languageCode = "en-us"
paginate = 10
theme = "hugo-xmin"
title = "Tiernan's Comms Closet"
enableGitInfo = true

[outputs]
home = ["HTML", "CSS", "RSS", "JSON"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]

[params]
description = "homepage of Tiernan OToole, Geek, photographer, GeekPhotographer, and lazy git."
tagline = "morning..."
feedlinks = true
cloudinary_url = "https://res.cloudinary.com/tiernanotoole/image/upload/"
leftsidebar = true

[params.sidebar]
order = ["search", "recent", "categories", "taglist"]

[params.widgets]
tags = true
search = false
recent_articles = true

[params.iubenda]
fit = "auto"
id = "21904595"

[params.social]
    github = "tiernano"
    reddit = "tiernanotoole"
    spotify = "tiernano"
    twitter = "tiernano"





