PygmentsCodeFences = true
PygmentsUseClasses = true
baseurl = "https://tiernano.github.io/www.tiernanotoole.ie_hugo_static/"
enableRobotsTXT = true
languageCode = "en-us"
paginate = 10
theme = "zen"
title = "Tiernan's Comms Closet "
[outputs]
home = ["HTML", "CSS", "RSS", "JSON"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
[params]
description = "homepage of Tiernan OToole, Geek, photographer, GeekPhotographer, and lazy git."
post_navigation = true
tagline = "morning..."
[params.iubenda]
fit = "auto"
id = "21904595"
[params.sidebar]
order = ["search", "recent", "categories", "taglist"]
cloudinary_url = "https://res.cloudinary.com/tiernanotoole/image/upload/"

