PygmentsUseClasses = false
PygmentsStyle = "colorful"
baseurl = "https://www.tiernanotoole.ie/"
enableRobotsTXT = true
languageCode = "en-us"
paginate = 10
theme = "theme-hugo-foundation6"
title = "Tiernan's Comms Closet"
enableGitInfo = true
googleAnalytics = "UA-220614-15"
disqusShortname = "tiernanotooleie"
Copyright = "2018 Tiernan OToole"
uglyUrls = true

[permalinks]
post = "/:year/:month/:day/:slug"

[outputs]
home = ["HTML", "CSS", "RSS", "JSON"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]

[params]
description = "Geek, Programmer, Photographer..."
tagline = "morning..."
feedlinks = true
cloudinary_base_url = "https://res.cloudinary.com/tiernanotoole/image/upload/"
leftsidebar = true
custom_navbar = true
ghrepo = "https://github.com/tiernano/www.tiernanotoole.ie_hugo/"


[[menu.sidebar]]
  name = "Link 1"
  url = "https://example.com"

[[menu.sidebar]]
  name = "Link 2"
  url = "https://example.org"

[[menu.navbar]]
  name = "Link 1"
  url = "https://example.org"

[params.sidebar]
# Optional about block for sidebar (can be Markdown)
about = "homepage of Tiernan OToole, Geek, photographer, GeekPhotographer, and lazy git."

# How many posts to show on the sidebar (Default: 5)
num_recent_posts = 10
order = ["search", "recent", "categories", "taglist"]

[params.widgets]
tags = true
search = false
recent_articles = true

[params.iubenda]
fit = "auto"
id = "21904595"

[params.social]
    github = "tiernano"
    reddit = "tiernanotoole"
    spotify = "tiernano"
    twitter = "tiernano"





