---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: https://hooks.slack.com/services/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
sections:
- path: content/computers
  label: Computers
  create: all
- path: content
  label: Pages
  create: all
- path: content/post
  label: Post
  create: all
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: '0.43'
